"""add is_active to departments

Revision ID: 65d83a89d95a
Revises: b61872ba45d3
Create Date: 2026-07-26 10:07:10.276195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d83a89d95a'
down_revision: Union[str, Sequence[str], None] = 'b61872ba45d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE departments ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT 'true' NOT NULL")    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'is_active')
    # ### end Alembic commands ###
