"""add is_verified to users

Revision ID: e5924cbf914f
Revises: 
Create Date: 2026-06-27 00:37:53.692894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5924cbf914f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constraints_master',
    sa.Column('constraint_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('constraint_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('constraint_id')
    )
    op.create_table('departments',
    sa.Column('department_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_name', sa.String(length=100), nullable=False),
    sa.Column('department_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('department_name')
    )
    op.create_table('strategies',
    sa.Column('strategy_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('strategy_id'),
    sa.UniqueConstraint('strategy_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('decisions',
    sa.Column('decision_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('decision_desc', sa.Text(), nullable=False),
    sa.Column('decision_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('draft', 'approved', 'implemented', 'completed', 'cancelled', name='decisionstatusenum'), nullable=False),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_table('decision_constraints',
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('constraint_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['constraint_id'], ['constraints_master.constraint_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.decision_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('decision_id', 'constraint_id')
    )
    op.create_table('decision_strategies',
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.decision_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.strategy_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('decision_id', 'strategy_id')
    )
    op.create_table('documents',
    sa.Column('document_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('upload_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.decision_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('outcomes',
    sa.Column('outcome_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('outcome_status', sa.Enum('successful', 'partially_successful', 'failed', name='outcomestatusenum'), nullable=False),
    sa.Column('outcome_desc', sa.Text(), nullable=True),
    sa.Column('success_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('evaluation_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.decision_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('outcome_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outcomes')
    op.drop_table('documents')
    op.drop_table('decision_strategies')
    op.drop_table('decision_constraints')
    op.drop_table('decisions')
    op.drop_table('users')
    op.drop_table('strategies')
    op.drop_table('departments')
    op.drop_table('constraints_master')
    # ### end Alembic commands ###
